services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SQL_Server_Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver:/init
      - sqlserver_data:/var/opt/mssql
    entrypoint: /bin/bash /init/docker-entrypoint-init.sh

  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2222
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/models.txt:/models.txt
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 5 &&
        cat /models.txt | xargs -n 1 ollama pull &&
        wait
      "

  api:
    build:
      context: .
      dockerfile: RealEstateAnalysis.API/Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__RealEstateManagementDB=Server=sqlserver;Database=RealEstateDB;User Id=sa;Password=SQL_Server_Password123!;TrustServerCertificate=True;
      - Jwt__Key=thisisaverylongandsecurestring!@#$%^&*()

  chatbot:
    build:
      context: ./AI-processing Services/real_estate_chatbot
      dockerfile: Dockerfile.chatbot
    container_name: chatbot
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
      - postgres
      - ollama
    env_file:
      - ./AI-processing Services/real_estate_chatbot/.env
    environment:
      - SQLSERVER_CONN_STR=Driver={ODBC Driver 17 for SQL Server};Server=sqlserver;Database=RealEstateDB;Uid=sa;Pwd=SQL_Server_Password123!;TrustServerCertificate=yes
      - POSTGRES_CONN_STR=postgresql://postgres:2222@postgres:5432/ai_property_db
      - APP_URL=http://client

  client:
    build:
      context: .
      dockerfile: RealEstateAnalysis.Client/Dockerfile.client
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiBaseUrl=http://api
      - ChatApiBaseUrl=http://chatbot:8000

  etl:
    build:
      context: ./AI-processing Services/property_etl_service
      dockerfile: Dockerfile.etl
    container_name: etl
    depends_on:
      - sqlserver
      - postgres
      - ollama
    env_file:
      - ./AI-processing Services/property_etl_service/.env
    environment:
      - SQLSERVER_CONN_STR=Driver={ODBC Driver 17 for SQL Server};Server=sqlserver;Database=RealEstateDB;Uid=sa;Pwd=SQL_Server_Password123!;TrustServerCertificate=yes
      - POSTGRES_CONN_STR=postgresql://postgres:2222@postgres:5432/ai_property_db
      - OLLAMA_API=http://ollama:11434

volumes:
  sqlserver_data:
  postgres_data:
  ollama_data: