version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SQL_Server_Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver:/init
      - sqlserver_data:/var/opt/mssql
    entrypoint: /bin/bash /init/docker-entrypoint-init.sh

  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2729
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/models.txt:/models.txt
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 5 &&
        cat /models.txt | xargs -n 1 ollama pull &&
        wait
      "

  api:
    build:
      context: .
      dockerfile: RealEstateAnalysis.API/Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__RealEstateManagementDB=Server=sqlserver;Database=RealEstateDB;User Id=sa;Password=SQL_Server_Password123!;TrustServerCertificate=True;
      - Jwt__Key=thisisaverylongandsecurestring!@#$%^&*()

volumes:
  sqlserver_data:
  postgres_data:
  ollama_data: